metadata:
  image.type: 'montjoie-ci'
  image.url: https://__BOOT_FQDN__/result/__PATCH__
  kernel.tree: mainline
  kernel.version: __KVERSION__
  kernel.endian: __KENDIAN__
  kernel.defconfig: montjoie_defconfig
  kernel.defconfig_base: montjoie_defconfig
  kernel.arch_defconfig: __ARCH__-montjoie_defconfig
  platform.dtb: __DTB__
  platform.dtb_short: __DTB__
  platform.fastboot: false
  platform.name: __DEVICETYPE__
  platform.mach: __MACH__
  test.plan: boot
  git.commit: __GIT_LASTCOMMIT__
  git.describe: __GIT_DESCRIBE__
  git.branch: master
  git.url: http://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
  device.type: __DEVICETYPE__
  job.arch: __ARCH__
  job.name: __JOBNAME__
  job.kernel_url: http://__BOOT_FQDN__/__PATH__/__KERNELFILE__
  job.kernel_image: __KERNELFILE__
  job.modules_url: http://__BOOT_FQDN__/__PATH__/module.tar.gz
  job.initrd_url: http://kernel.montjoie.ovh/rootfs/__ARCHENDIAN__/rootfs.cpio.gz
  job.nfsrootfs_url: None
  job.dtb_url: http://__BOOT_FQDN__/__PATH__/dts/__DTB__

device_type: __DEVICETYPE__

notify:
  criteria:
    status: finished

job_name: __JOBNAME__
timeouts:
  job:
    minutes: 15
  action:
   minutes: 15
  actions:
    power-off:
      seconds: 30
priority: high
visibility: public

actions:
- deploy:
    timeout:
      minutes: 10
    to: tftp
    kernel:
      url: __BOOT_FQDN__/__PATH__/__KERNELFILE__
      type: __KERNELTYPE__
    ramdisk:
      url: __ROOT_FQDN__/rootfs/__ARCHENDIAN__/rootfs.cpio.gz
      compression: gz
    modules:
      url: __BOOT_FQDN__/__PATH__/modules.tar.gz
      compression: gz
    dtb:
      url: __BOOT_FQDN__/__PATH__/dts/__DTB__
    os: oe

- boot:
    timeout:
      minutes: 5
    method: u-boot
    commands: ramdisk
    prompts:
      - '/ #'

- test:
    timeout:
        minutes: 15
    definitions:
        - repository: https://github.com/montjoie/lava-tests.git
          from: git
          path: execs/boot.yaml
          name: Boot
        - repository: https://github.com/montjoie/lava-tests.git
          from: git
          path: execs/network.yaml
          name: Network
        - repository: https://github.com/montjoie/lava-tests.git
          from: git
          path: execs/hardware.yaml
          name: Hardware
        - repository: https://github.com/montjoie/lava-tests.git
          from: git
          path: execs/crypto.yaml
          name: Crypto
        - repository: https://github.com/montjoie/lava-tests.git
          from: git
          path: execs/misc.yaml
          name: Misc
